//! Source layers, lowest first. Every source has one explicit place.
const gantry = @import("gantry");

pub const layers: []const gantry.rules.Layer = &.{
    .{ .name = "primitives", .patterns = &.{
        "src/builtins.zig",
        "src/jsonc.zig",
        "src/owned_slice.zig",
        "src/path.zig",
        "src/scan_diagnostic.zig",
        "src/types.zig",
    } },
    .{ .name = "storage and matching", .patterns = &.{
        "src/Analysis/analysis_store.zig",
        "src/Imports/import_store.zig",
        "src/lexer.zig",
        "src/Analysis/reach.zig",
        "src/resolve_path.zig",
        "src/rules/rules_check.zig",
        "src/scan_reader.zig",
    } },
    .{ .name = "recovery and configuration", .patterns = &.{
        "src/Imports.zig",
        "src/go_build.zig",
        "src/go_config.zig",
        "src/manifests/**",
        "src/lang/c.zig",
        "src/lang/java.zig",
        "src/lang/nim.zig",
        "src/lang/python.zig",
        "src/lang/rust.zig",
        "src/lang/zig.zig",
        "src/manifests.zig",
        "src/nim_config.zig",
        "src/tokens.zig",
        "src/tsconfig.zig",
    } },
    .{ .name = "graph storage and language policy", .patterns = &.{
        "src/code_kind.zig",
        "src/Graph/graph_store.zig",
        "src/java_packages.zig",
        "src/lang/go.zig",
        "src/lang/javascript.zig",
        "src/python_exports.zig",
    } },
    .{ .name = "analysis and language dispatch", .patterns = &.{
        "src/Analysis/analyze.zig",
        "src/languages.zig",
    } },
    .{ .name = "resolution", .patterns = &.{
        "src/Analysis.zig",
        "src/resolve.zig",
    } },
    .{ .name = "owners and scan policy", .patterns = &.{
        "src/Graph.zig",
        "src/rules/dependency_check.zig",
        "src/recover.zig",
        "src/scan_options.zig",
    } },
    .{ .name = "scanning", .patterns = &.{
        "src/rules.zig",
        "src/scan.zig",
    } },
    .{ .name = "reports", .patterns = &.{
        "src/report.zig",
        "src/report/**",
    } },
    .{ .name = "public", .patterns = &.{
        "src/gantry.zig",
    } },
    .{ .name = "fixtures", .patterns = &.{
        "src/lexers_test.zig",
        "src/properties_test.zig",
        "src/testing/**",
    } },
    .{ .name = "scenarios", .patterns = &.{
        "src/configs_test.zig",
        "src/constraints_test.zig",
        "src/dependencies_test.zig",
        "src/fuzz_test.zig",
        "src/go_modules_test.zig",
        "src/graph_test.zig",
        "src/java_test.zig",
        "src/kinds_test.zig",
        "src/manifests_test.zig",
        "src/memory_test.zig",
        "src/nim_test.zig",
        "src/python_policy_test.zig",
        "src/queries_test.zig",
        "src/recovery_test.zig",
        "src/report_test.zig",
        "src/resolution_test.zig",
        "src/rules_test.zig",
        "src/scan_diagnostic_test.zig",
        "src/tokens_test.zig",
        "src/unsupported_test.zig",
    } },
    .{ .name = "tests", .patterns = &.{
        "src/tests.zig",
    } },
};

pub const entries: []const []const u8 = &.{};

pub const modules: []const gantry.NamedModule = &.{};

pub const references: []const gantry.rules.ReferenceRule = &.{
    .{ .name = "named dependencies", .unresolved_only = true, .except_targets = &.{
        "std",
    } },
    .{ .name = "source siblings", .suffix = ".zig", .relative = true, .except_targets = &.{"src/**"} },
};

pub const required = [_][]const u8{
    "src/builtins.zig",
    "src/jsonc.zig",
    "src/owned_slice.zig",
    "src/path.zig",
    "src/scan_diagnostic.zig",
    "src/types.zig",
    "src/Analysis/analysis_store.zig",
    "src/Imports/import_store.zig",
    "src/lexer.zig",
    "src/Analysis/reach.zig",
    "src/resolve_path.zig",
    "src/rules/rules_check.zig",
    "src/scan_reader.zig",
    "src/Imports.zig",
    "src/go_build.zig",
    "src/go_config.zig",
    "src/manifests/gradle.zig",
    "src/lang/c.zig",
    "src/lang/java.zig",
    "src/lang/nim.zig",
    "src/lang/python.zig",
    "src/lang/rust.zig",
    "src/lang/zig.zig",
    "src/manifests.zig",
    "src/manifests/maven.zig",
    "src/nim_config.zig",
    "src/manifests/nimble.zig",
    "src/tokens.zig",
    "src/tsconfig.zig",
    "src/code_kind.zig",
    "src/Graph/graph_store.zig",
    "src/java_packages.zig",
    "src/lang/go.zig",
    "src/lang/javascript.zig",
    "src/python_exports.zig",
    "src/Analysis/analyze.zig",
    "src/languages.zig",
    "src/Analysis.zig",
    "src/resolve.zig",
    "src/Graph.zig",
    "src/rules/dependency_check.zig",
    "src/recover.zig",
    "src/scan_options.zig",
    "src/rules.zig",
    "src/scan.zig",
    "src/report.zig",
    "src/report/report_json.zig",
    "src/gantry.zig",
    "src/lexers_test.zig",
    "src/properties_test.zig",
    "src/testing/test_support.zig",
    "src/configs_test.zig",
    "src/constraints_test.zig",
    "src/dependencies_test.zig",
    "src/fuzz_test.zig",
    "src/go_modules_test.zig",
    "src/graph_test.zig",
    "src/java_test.zig",
    "src/kinds_test.zig",
    "src/manifests_test.zig",
    "src/memory_test.zig",
    "src/nim_test.zig",
    "src/python_policy_test.zig",
    "src/queries_test.zig",
    "src/recovery_test.zig",
    "src/report_test.zig",
    "src/resolution_test.zig",
    "src/rules_test.zig",
    "src/scan_diagnostic_test.zig",
    "src/tokens_test.zig",
    "src/unsupported_test.zig",
    "src/tests.zig",
};
