//! Source layers, lowest first. Every source has one explicit place.
const gantry = @import("gantry");

pub const layers: []const gantry.rules.Layer = &.{
    .{ .name = "primitives", .patterns = &.{
        "src/builtins.zig",
        "src/jsonc.zig",
        "src/owned_slice.zig",
        "src/path.zig",
        "src/scan/diagnostic.zig",
        "src/types.zig",
    } },
    .{ .name = "storage and matching", .patterns = &.{
        "src/Analysis/state.zig",
        "src/Imports/state.zig",
        "src/lexer.zig",
        "src/Analysis/reach.zig",
        "src/resolve/path.zig",
        "src/rules/check.zig",
        "src/scan/reader.zig",
    } },
    .{ .name = "recovery and configuration", .patterns = &.{
        "src/Imports.zig",
        "src/lang/go/build.zig",
        "src/lang/go/config.zig",
        "src/manifests/**",
        "src/lang/c.zig",
        "src/lang/java.zig",
        "src/lang/nim.zig",
        "src/lang/python.zig",
        "src/lang/rust.zig",
        "src/lang/zig.zig",
        "src/manifests.zig",
        "src/lang/nim/config.zig",
        "src/tokens.zig",
        "src/tsconfig.zig",
    } },
    .{ .name = "graph storage and language policy", .patterns = &.{
        "src/code_kind.zig",
        "src/Graph/storage.zig",
        "src/lang/java/packages.zig",
        "src/lang/go.zig",
        "src/lang/javascript.zig",
        "src/lang/python/exports.zig",
    } },
    .{ .name = "analysis and language dispatch", .patterns = &.{
        "src/Analysis/analyze.zig",
        "src/languages.zig",
    } },
    .{ .name = "resolution", .patterns = &.{
        "src/Analysis.zig",
        "src/resolve.zig",
    } },
    .{ .name = "owners and scan policy", .patterns = &.{
        "src/Graph.zig",
        "src/rules/dependency_check.zig",
        "src/recover.zig",
        "src/scan/options.zig",
    } },
    .{ .name = "scanning", .patterns = &.{
        "src/rules.zig",
        "src/scan.zig",
    } },
    .{ .name = "reports", .patterns = &.{
        "src/report.zig",
        "src/report/**",
    } },
    .{ .name = "public", .patterns = &.{
        "src/gantry.zig",
    } },
    .{ .name = "fixtures", .patterns = &.{
        "src/testing/lexers_test.zig",
        "src/testing/properties_test.zig",
        "src/testing/support.zig",
    } },
    .{ .name = "scenarios", .patterns = &.{
        "src/testing/configs_test.zig",
        "src/testing/constraints_test.zig",
        "src/testing/dependencies_test.zig",
        "src/testing/fuzz_test.zig",
        "src/testing/go_modules_test.zig",
        "src/Graph_test.zig",
        "src/lang/java_test.zig",
        "src/testing/kinds_test.zig",
        "src/manifests_test.zig",
        "src/testing/memory_test.zig",
        "src/lang/nim_test.zig",
        "src/testing/python_policy_test.zig",
        "src/testing/queries_test.zig",
        "src/testing/recovery_test.zig",
        "src/report_test.zig",
        "src/testing/resolution_test.zig",
        "src/rules_test.zig",
        "src/scan/diagnostic_test.zig",
        "src/tokens_test.zig",
        "src/testing/unsupported_test.zig",
    } },
    .{ .name = "tests", .patterns = &.{
        "src/tests.zig",
    } },
};

pub const entries: []const []const u8 = &.{};

pub const modules: []const gantry.NamedModule = &.{};

pub const references: []const gantry.rules.ReferenceRule = &.{
    .{ .name = "named dependencies", .unresolved_only = true, .except_targets = &.{
        "std",
    } },
    .{ .name = "source siblings", .suffix = ".zig", .relative = true, .except_targets = &.{"src/**"} },
};

pub const required = [_][]const u8{
    "src/builtins.zig",
    "src/jsonc.zig",
    "src/owned_slice.zig",
    "src/path.zig",
    "src/scan/diagnostic.zig",
    "src/types.zig",
    "src/Analysis/state.zig",
    "src/Imports/state.zig",
    "src/lexer.zig",
    "src/Analysis/reach.zig",
    "src/resolve/path.zig",
    "src/rules/check.zig",
    "src/scan/reader.zig",
    "src/Imports.zig",
    "src/lang/go/build.zig",
    "src/lang/go/config.zig",
    "src/manifests/gradle.zig",
    "src/lang/c.zig",
    "src/lang/java.zig",
    "src/lang/nim.zig",
    "src/lang/python.zig",
    "src/lang/rust.zig",
    "src/lang/zig.zig",
    "src/manifests.zig",
    "src/manifests/maven.zig",
    "src/lang/nim/config.zig",
    "src/manifests/nimble.zig",
    "src/tokens.zig",
    "src/tsconfig.zig",
    "src/code_kind.zig",
    "src/Graph/storage.zig",
    "src/lang/java/packages.zig",
    "src/lang/go.zig",
    "src/lang/javascript.zig",
    "src/lang/python/exports.zig",
    "src/Analysis/analyze.zig",
    "src/languages.zig",
    "src/Analysis.zig",
    "src/resolve.zig",
    "src/Graph.zig",
    "src/rules/dependency_check.zig",
    "src/recover.zig",
    "src/scan/options.zig",
    "src/rules.zig",
    "src/scan.zig",
    "src/report.zig",
    "src/report/json.zig",
    "src/gantry.zig",
    "src/testing/lexers_test.zig",
    "src/testing/properties_test.zig",
    "src/testing/support.zig",
    "src/testing/configs_test.zig",
    "src/testing/constraints_test.zig",
    "src/testing/dependencies_test.zig",
    "src/testing/fuzz_test.zig",
    "src/testing/go_modules_test.zig",
    "src/Graph_test.zig",
    "src/lang/java_test.zig",
    "src/testing/kinds_test.zig",
    "src/manifests_test.zig",
    "src/testing/memory_test.zig",
    "src/lang/nim_test.zig",
    "src/testing/python_policy_test.zig",
    "src/testing/queries_test.zig",
    "src/testing/recovery_test.zig",
    "src/report_test.zig",
    "src/testing/resolution_test.zig",
    "src/rules_test.zig",
    "src/scan/diagnostic_test.zig",
    "src/tokens_test.zig",
    "src/testing/unsupported_test.zig",
    "src/tests.zig",
};
